# --- BÖLÜM 1: MARIO 1-1 ---
LEVEL_1_MAP = [
    "                                                                                                                                                                                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                 ",
    "                              K K K                                                                                       KKK                                                                                                       ",
    "                              K K K                                                                                       KFK                                                                                                       ",
    "                          KKKKKKKKKKKKK                                                                                  KKKKK                                                                                                      ",
    "                                                                                                                        KKKKKKK                                                                                                     ",
    "               K            K        K                                                                                 KKKKKKKKK                                                                                                    ",
    "              KKK          KKK       K  D                           K  K  K                                            KKKKKKKKKKK                                                                                                   ",
    "             KKKKK  K  K  K   K  K   KKKKK      K                    K  K  K                            XXXX          KKKKKKKKKKKKK                                                                                                  ",
    "            KKKKKKK K D K  K   K  K  KKKKKKK                          KKKKKKKKKKKK      S                 XX         KKKKKKKKKKKKKKK                                                                                                 ",
    " XXXXX  K  KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK  K  XX  K K  K  K   K XX  K K  K  K KKKKKKKKKKKKK   KK  K    K   K   K   K   K  K  K  K   K  K   K  XXX  K   XXX  KK   K   K  KXXXK   K  K  K  K  KKKKKKKKKKKKKKKKKK                    ",
    " XXXXXWWKWWKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKWWWWWWXXWWWWWWWWWWWWWWWWXXWWWWWTWWWWWWKKKKKKKKKKKK  T W   WT TW    WTTWWWW WTTWWWW TWWWW TTWWWW TWWW TXXXX  T   XX  WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW  KKKKKKKKKKKKKKKKKKK F                  ",
    " XXXXXWWWWWKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKWWWWWWXXXWWWWWWWWWWWWWWWXXXWWWWWWWWWWWKKKKKKKKKKKK                  XX                       XXXXX      XXX         D                           KKKKKKKKKKKKKKKKKKKKK   FFF                  ",
    " XXXXXWWWWWKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKWWWWWWXXXWWWWWWWWWWWWWWWXXXWWWWWWWWWWWKKKKKKKKKKKK                  XX                      XXXXXX      XXX                                    KKKKKKKKKKKKKKKKKKKKKKK  FFFFF                  ",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  WW WW  XXXXXXXXXXXXXXX  WW WW  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  WW WW  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTTTTTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT  WW WW  TTTTTTTTTTTTTTT  WW WW  TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT  WW WW  TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
]

# --- BÖLÜM 2: DÜZLÜK VE ÖRDEK (NPC) ---
LEVEL_2_MAP = [
    "                                                                                                                                                                                                ",
    "                                                                                                                                                                                                ",
    "                                                                                                                                                                                                ",
    "                                                                                                                                                                                                ",
    "                                                                                                                                                                                                ",
    "                                                                                                                                                                                                ",
    "                                                                                                                                                                                                ",
    "                                                                                                                                                                                                ",
    "                                                                                                                                                                                                ",
    "                                                                                                                                                                                                ",
    "                                                                                                                                                                                                ",
    "                                                                                                                                                                                                ",
    "                                                                                                                                                                                                ",
    "                                           N                                                                                   F                                                                 ",
    " XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                         ",
    " TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                                         ",
    " TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT                                                         ",
]

# --- BÖLÜM 3: CO-OP CHALLENGE ---
LEVEL_3_MAP = [
    "                                                                                                                                                                                                ",
    "                                                                                                                                                                                                ",
    "                                                                                                                                                                                                ",
    "                                                                                                                                                                                                ",
    "                                                                                                                                                                                                ",
    "                                                                                                                                                                                                ",
    "                                                                         K                                                                                                                      ",
    "                                                                        KKK                                                                                                                     ",
    "                  K                                                    KKKKK                                                        F                                                           ",
    "                 KKK                                                 KKKKKKK                 D                                    FFF                                                          ",
    "                KKKKK      XXXX                                      KKKKKKKKK               XXXX                                 FFFFF                                                         ",
    "               KKKKKKK   K TTTT      D          K                   KKKKKKKKKKK             KTTTT                                FFFFFFF                                                        ",
    " XX    D      KKKKKKKKK    TTTT  K   K    K    KKK   K    K    K   KKKKKKKKKKKKK   K  K  K   TTTT  K   K   XX     K    K XX     FFFFFFFFF                                                       ",
    " XXKK XXXX   KKKKKKKKKKK   TTTT   W     W     KKKKK     W    W    KKKKKKKKKKKKKKK    W    W  TTTT   W      XX  W      W  XX    FFFFFFFFFFF                                                      ",
    " XX  WTTTT  KKKKKKKKKKKKK  TTTT  WWW   WWW   KKKKKKK   WWW  WWW  KKKKKKKKKKKKKKKKK  WWW  WWW TTTT  WWW    XXXXWWW    WWWXXXX   TTTTTTTTTTT                                                      ",
    "XXXX  TTTT  TTTTTTTTTTTTT  TTTT  WWWWWWWWW  KKKKKKKKK  WWWWWWWW  TTTTTTTTTTTTTTTTT  WWWWWWWW TTTT  WWWW  XXXXXXWWWW  WWXXXXXX  TTTTTTTTTTT                                                      ",
    "TTTT  TTTT  TTTTTTTTTTTTT  TTTT  WWWWWWWWW  TTTTTTTTT  WWWWWWWW  TTTTTTTTTTTTTTTTT  WWWWWWWW TTTT  WWWW  TTTTTTWWWW  WWTTTTTT  TTTTTTTTTTT                                                      ",
    "TTTT  TTTT  TTTTTTTTTTTTT  TTTT  WWWWWWWWW  TTTTTTTTT  WWWWWWWW  TTTTTTTTTTTTTTTTT  WWWWWWWW TTTT  WWWW  TTTTTTWWWW  WWTTTTTT  TTTTTTTTTTT                                                      ",
    "TTTT  TTTT  TTTTTTTTTTTTT  TTTT  WWWWWWWWW  TTTTTTTTT  WWWWWWWW  TTTTTTTTTTTTTTTTT  WWWWWWWW TTTT  WWWW  TTTTTTWWWW  WWTTTTTT  TTTTTTTTTTT                                                      ",
    "TTTT  TTTT  TTTTTTTTTTTTT  TTTT  WWWWWWWWW  TTTTTTTTT  WWWWWWWW  TTTTTTTTTTTTTTTTT  WWWWWWWW TTTT  WWWW  TTTTTTWWWW  WWTTTTTT  TTTTTTTTTTT                                                      ",
]
# --- BÖLÜM 4: MARTI KURTARMA (DİKEY) ---
LEVEL_4_MAP = [
    "                                                                                                                      ",
    "                                                    N                                                                 ",
    "                                                  KKKKK                                                               ",
    "                                                  K   K                                                               ",
    "                                       K          K   K        K                                                      ",
    "                                      KKK         KKKKK       KKK                                           F        ",
    "                                     KKKKK                   KKKKK                                         FFF       ",
    "                   K                KKKKKKK                 KKKKKKK                                       FFFFF      ",
    "                  KKK              KKKKKKKKK               KKKKKKKKK                                     FFFFFFF     ",
    "                 KKKKK            KKKKKKKKKKK             KKKKKKKKKKK                                   FFFFFFFFF    ",
    "                KKKKKKK          KKKKKKKKKKKKK           KKKKKKKKKKKKK                                 FFFFFFFFFFF   ",
    "               KKKKKKKKK        KKKKKKKKKKKKKKK         KKKKKKKKKKKKKKK                                TTTTTTTTTTT    ",
    "              KKKKKKKKKKK      KKKKKKKKKKKKKKKKK       KKKKKKKKKKKKKKKKK                               TTTTTTTTTTT    ",
    "             KKKKKKKKKKKKK    KKKKKKKKKKKKKKKKKKK     KKKKKKKKKKKKKKKKKKK                           K  TTTTTTTTTTT    ",
    "            KKKKKKKKKKKKKKK  KKKKKKKKKKKKKKKKKKKKK   KKKKKKKKKKKKKKKKKKKKK                             TTTTTTTTTTT    ",
    "    K      KKKKKKKKKKKKKKKKK KKKKKKKKKKKKKKKKKKKKK   KKKKKKKKKKKKKKKKKKKKK      G                 K    TTTTTTTTTTT    ",
    "   KKK    KKKKKKKKKKKKKKKKKK KKKKKKKKKKKKKKKKKKKKK   KKKKKKKKKKKKKKKKKKKKK   WWKKKWWW   K    K         TTTTTTTTTTT    ",
    "  KKKKK   TTTTTTTTTTTTTTTTTT TTTTTTTTTTTTTTTTTTTTT   TTTTTTTTTTTTTTTTTTTTT   WWWWWWWW        K         TTTTTTTTTTT    ",
    " XXXXXXX  TTTTTTTTTTTTTTTTTT TTTTTTTTTTTTTTTTTTTTT   TTTTTTTTTTTTTTTTTTTTT   WWWWWWWW        W         TTTTTTTTTTT    ",
    " TTTTTTT  TTTTTTTTTTTTTTTTTT TTTTTTTTTTTTTTTTTTTTT   TTTTTTTTTTTTTTTTTTTTT   WWWWWWWW        W         TTTTTTTTTTT    ",
]
# LEVEL 5
LEVEL_5_MAP = [
    "                                                                                                                                                                                                ",
    "                                                                                                                                                                                                ",
    "                                          F                                                                                                                                                     ",
    "                                         FFF                                                                                                                                                    ",
    "                                        FFFFF                                                                                                                                                   ",
    "                                       FFFFFFF                                                                                                                                                  ",
    "                 K                    FFFFFFFFF                                                                                                                                                 ",
    "                KKK                  TTTTTTTTTTT                                                                                                                                                ",
    "               KKKKK                 TTTTTTTTTTT                                                                                                                                                ",
    "              KKKKKKK            K   TTTTTTTTTTT                                                                                                                                                ",
    "             KKKKKKKKK               TTTTTTTTTTT                                                                                                                                                ",
    "            KKKKKKKKKKK              TTTTTTTTTTT                                                                                                                                                ",
    "           KKKKKKKKKKKKK             TTTTTTTTTTT                                                                                                                                                ",
    "          KKKKKKKKKKKKKKK            TTTTTTTTTTT                                                                                                                                                ",
    "         KKKKKKKKKKKKKKKKK           TTTTTTTTTTT                                                                                                                                                ",
    "        KKKKKKKKKKKKKKKKKKK          TTTTTTTTTTT         D          D          D                                                                                                            ",
    "       KKKKKKKKKKKKKKKKKKKKK         TTTTTTTTTTT        XXX        XXX        XXX                                                                                                           ",
    "      KKKKKKKKKKKKKKKKKKKKKKK        TTTTTTTTTTT       XXXXX      XXXXX      XXXXX                                                                                                          ",
    "     KKKKKKKKKKKKKKKKKKKKKKKKK       TTTTTTTTTTT      XXXXXXX    XXXXXXX    XXXXXXX                                                                                                         ",
    "    KKKKKKKKKKKKKKKKKKKKKKKKKKK      TTTTTTTTTTT     XXXXXXXXX  XXXXXXXXX  XXXXXXXXX                                                                                                        ",
]
# --- BÖLÜM 6: HIZ PARKURU (TWI SHOWCASE) ---
LEVEL_6_MAP = [
    "                                                                                                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                ",
    "                 N                                                                                                                                                                                                                              ",
    "               KKKKK                                                                                                                                                                                                                            ",
    "               K   K                                                                                                                                                                                                                            ",
    "               K   K                                                                                                                                                                                                                            ",
    "              KKKKKKK                 K      K                  K                                                                                                                                                                           ",
    "             KKKKKKKKK            D  KKK    KKK  D             KKK                         K  K  K                                      K                                                                                                                       ",
    "            KKKKKKKKKKK          XXXKKKKK  KKKKKXXX           KKKKK            D                     KKKKKKKKK                                    KKK                                                                                                                      ",
    "           KKKKKKKKKKKKK        XXXXKKKKK  KKKKKXXXX         KKKKKKK          XXX                   KKKKKKKKKKK                                  KKKKK                                                F                                                                    ",
    "          KKKKKKKKKKKKKKK      XXXXXKKKKK  KKKKKXXXXX       KKKKKKKKK        XXXXX                 KKKKKKKKKKKKK                                KKKKKKK                                              FFF                                                                   ",
    "         KKKKKKKKKKKKKKKKK    XXXXXXKKKKK  KKKKKXXXXXX     KKKKKKKKKKK      XXXXXXX               KKKKKKKKKKKKKKK                              KKKKKKKKK            D             D                 FFFFF                                                                  ",
    " XXXXX  KKKKKKKKKKKKKKKKKKK  XXXXXXX            XXXXXXX   KKKKKKKKKKKKK    XXXXXXXXX    K  K  K  KKKKKKKKKKKKKKKKK   WWWWWWWWWWWWWW   K  K  K KKKKKKKKKKK        XXX           XXX               FFFFFFF                                                                 ",
    " TTTTT  TTTTTTTTTTTTTTTTTTT  XXXXXXX            XXXXXXX   TTTTTTTTTTTTT    XXXXXXXXX    TTTTTTT  TTTTTTTTTTTTTTTTT   WWWWWWWWWWWWWW   TTTTTTT TTTTTTTTTTT       XXXXX         XXXXX             FFFFFFFFF                                                                ",
]

# --- BÖLÜM 7: TUKAN (HIZ VE MOMENTUM) ---
LEVEL_7_MAP = [
    "                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                        ",
    "          N                                                                                                                                                                                                                                                                              ",
    "        KKKKK                                                                                                                                                                                                                                                                           ",
    "        K   K                                                                                                                                                                                                                                                                           ",
    "        K   K                                                                                                                                                                                                                                                                           ",
    "       KKKKKKK                                                                                                                                                                                                                                                                          ",
    "      KKKKKKKKK                                                                                                                                                                                                                                                                         ",
    "     KKKKKKKKKKK                                                                                                                                                                                                                                                                        ",
    "    KKKKKKKKKKKKK                                                                                                                                                                                                                                                                       ",
    "    KKKKKKKKKKKKK                                                                                                                                                                                                                                                                       ",
    "    KKKKKKKKKKKKK                                                                                                                                                                                                                                                                       ",
    "    KKKKKKKKKKKKK                                                                                                                                                                                                                                                                       ",
    "    KKKKKKKKKKKKK                                                                                                                                                                                                                                                                       ",
    "    KKKKKKKKKKKKK                                                                                                                                                                                                                                                                       ",
    "    KKKKKKKKKKKKK                                                                                                                                                                                                                                            F                          ",
    "    KKKKKKKKKKKKK                                                                                                                                                                                                                                           FFF                         ",
    "    TTTTTTTTTTTTT                                                  K                                                          K                                                            K                                                               FFFFF                        ",
    "    TTTTTTTTTTTTTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXK   WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWK   WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWK   WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWFFFFFFF                        ",
]